server {
    listen 80;
    listen [::]:80;
    server_name node21.webte.fei.stuba.sk;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name node21.webte.fei.stuba.sk;

    root /var/www/node21.webte.fei.stuba.sk/olympians_project;
    index index.php index.html;

    charset utf-8;
    client_max_body_size 16M;

    ssl_certificate /etc/letsencrypt/live/node21.webte.fei.stuba.sk/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/node21.webte.fei.stuba.sk/privkey.pem;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.4-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.ht {
        deny all;
    }
}
